/*
 * action types
 */

export const ADD_WIZARD = 'ADD_WIZARD';
export const EDIT_WIZARD = 'EDIT_WIZARD';
export const DELETE_WIZARD = 'DELETE_WIZARD';
export const CLICK_WIZARD = 'CLICK_WIZARD';
export const REQUEST_WIZARD = 'REQUEST_WIZARD';
export const REQUEST_UPDATE_WIZARD = 'REQUEST_UPDATE_WIZARD';
export const REDIRECT_WIZARD = 'REDIRECT_WIZARD';
export const RECEIVE_WIZARD = 'RECEIVE_WIZARD';
export const REQUEST_WIZARDS = 'REQUEST_WIZARDS';
export const RECEIVE_WIZARDS = 'RECEIVE_WIZARDS';

export const REPORT_NOT_FOUND = 'REPORT_NOT_FOUND';

export const DRAG_IN_WIZARD_FILE = 'DRAG_IN_WIZARD_FILE';
export const DRAG_OUT_WIZARD_FILE = 'DRAG_OUT_WIZARD_FILE';
export const START_UPLOAD_WIZARD_FILE = 'START_UPLOAD_WIZARD_FILE';
export const UPLOAD_WIZARD_FILE_SUCCESS = 'UPLOAD_WIZARD_FILE_SUCCESS';
export const UPLOAD_WIZARD_FILE_ERROR = 'UPLOAD_WIZARD_FILE_ERROR';
export const SHOW_DROP_ZONE = 'SHOW_DROP_ZONE';
export const HIDE_DROP_ZONE = 'HIDE_DROP_ZONE';
